### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by itsmethatswho** [Dandielo/DtlCitizensTrader#10]
Hey Dandielo, 

I know you're busy with the next update, but I was wondering if you were going to start adding your updates to dev.bukkit.org for the auto-updater.  I'm not sure how it works since I know Dtl Trader is in beta, but my bukkit GUI is giving me this notification, " No source for DtlCitizensTrader v1.9.61Beta ask the Author to add it to dev.bukkit.org "

Hope all is going well, thanks!

**Comment by Dandielo** [comment]
i will try to add it :)

**Comment by itsmethatswho** [comment]
yay! Thanks!

**Comment by Dandielo** [comment]
going to work on this now
