### ISSUE TITLE
Patterns Durability Question

### ISSUE THREAD

**Issue by itsmethatswho** [Dandielo/DtlCitizensTrader#11]
Hey Dandielo!

I just wanted to see if there was a simple way for me to input prices for damaged items in a pattern.  If I understand how it works correctly I would need to set a d: for each single value of durability loss, which would be hundreds and thousands of lines.  Is there anyway I can input the durability as an interval?  

i.e. For a Diamond sword if I want 25% intervals I could do d: 1562-1172 , d: 1171-781, d: 780-391, d:391-0.

Thanks!

**Comment by Dandielo** [comment]
Hmm... the whole think should check the durability like this: itemWeWantToSellDurability >== itemTraderIsBuyingDurability, if not it should go and search for the next 1, 
that means we should use in patterns sth like this

durability:
  items:
    buy:
    - 285 p:10 d:33 (is use here a golden pickaxe)
    - 285 p:50 d:22
    - 285 p:100 d:11

lets say i got a gPickaxe with durability 15

first it should check if 15 <= 11
if not then 15 <= 22 (it will stop here, so it will tell the user that the price for that pickaxe is 50)
if not then 33 <= 15 

But dunno why it's not working for me so I will fix so it will work as I said here :)

**Comment by Dandielo** [comment]
and you also need always to such a pattern from the worst durability to the best

so worst is 33 (it's already broken) and best would be 0 but we want the same price from 0-11 :) 

Btw I've uploaded a new version here on GitHub with the fixed durability issue

**Comment by itsmethatswho** [comment]
Ok I get it, thanks!
