### ISSUE TITLE
Strage behavior

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#13]
Hello there,

I got some strange behavior... I can configure the trader, but when I get out the server and login again, the trade windows won't appear anymore, I need to call /citizens reload, so I can rightclick again..

**Comment by Dandielo** [comment]
Hmm going to check this and fix as fast as i can :)

**Comment by cranic** [comment]
This was caused by and outdated version of Orebfuscator, the solution was to update it. Can be closed now.
