### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#14]
Ubuntu 12.04.1
CraftBukkit Spigot biuld #238
Citizens2 build #571
Denizen build #571
dtlTrader-2.0RCv0.73.jar

I setup the trader but when I try to test it picking up an iten to buy: https://gist.github.com/4101422

**Comment by cranic** [comment]
Well, as far as I could test, if I create a simple denizen NPC with those same configs, when I hit /citizens reload, it vanishes...

**Comment by Dandielo** [comment]
thx for the info, will look at it immediately

**Comment by cranic** [comment]
Thanks for the lightning speed response.
This is the plugin that will make our server different from other ones, as soon as we start profiting from VIPs and micropayments I'm sure that we will start to donate to the project.

**Comment by Dandielo** [comment]
Ok I found the glitch :) just need to finish my previous work and a n update is going to be uploaded soon :)

**Comment by Dandielo** [comment]
btw remove your old config, just changed it a bit, when you will look at it you should know what has bed added :)

**Comment by cranic** [comment]
Cool, let us know when the fix is out.

**Comment by Dandielo** [comment]
it's already alive :)

**Comment by Dandielo** [comment]
v0.74

**Comment by cranic** [comment]
Fine, I'm testing it right now.

**Comment by cranic** [comment]
Ok, now I can buy/sell, but if I exit the game and enter again, the trade window won't appear. If I hit /citizens reload the npc disapears... How can I help you to track back this? No error show up in the console...

#Update
As far as I could see, `/citizens reload` don't save the NPCs, I need to `/stop`, then Citizens saves all the NPCs and I can use `/citizens reload` without fear. But still we have the trade window problem..

**Comment by Dandielo** [comment]
hmm... it's always happening after a relog?

**Comment by Dandielo** [comment]
use /reload after you reloged not /citizens reload

**Comment by Dandielo** [comment]
hmm trade window is a bit complicated i can't get out why it's not working on your side. May i get on your server to look at it?

#Edit
Have you got any chat program, like skype? or may you get on my IRC, would be much easier go remove that bug :)

**Comment by cranic** [comment]
Off course, add me at skype alan_hoff, I'm configuring a testing VM with Hamachi and SSH access, so you can see the error :)

**Comment by Dandielo** [comment]
so fixed the buy glitch :)
