### ISSUE TITLE
RigthClick event issue with the last build

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#15]
Hey there!

I'm getting this error using the last build.
https://gist.github.com/4123117

Thx!

**Comment by Dandielo** [comment]
fixed :) next build is available for download in next few minutes :)

**Comment by cranic** [comment]
Awesome, I will test :D

**Comment by cranic** [comment]
The price isn't showing and a rain of enderpearls are falling from the sky on the top of every player... But the RightClick issue is corrected.. lol

**Comment by Dandielo** [comment]
lol sorry xD was testing some crap on this build xD going to put a correct one xD lol forgot about it

**Comment by Dandielo** [comment]
removed falling enderpearls and prices are now shown properly for traders without patterns set xd

**Comment by Dandielo** [comment]
a bulid is available to download :D

**Comment by cranic** [comment]
hahaha lol :P 
Thanks!

Edited: everything working now.
