### ISSUE TITLE
Idea - A plugin like this por personal shop

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#16]
Hello there,

What you think about a plugin just like this one, but instead of NPC the player could manage one shop for when other players right click them? It would be awesome!

It could tipe some command like /selfshop then the management windows would open, then he can place the itens that he is selling and buying :+1:

**Comment by Dandielo** [comment]
It is possible but I may do this when I got more time, atm I can only set this as a future project hut the idea is grate :)

**Comment by Dandielo** [comment]
Of for that project i need a whole description, so when your willing to help me a bit can you describe in details the wole idea? If ppl may enable/disable the trader function, if they may move etc...

**Comment by cranic** [comment]
- Players are able to move around
- Players can see the others buying/selling itens when right click other players
- They can manage buy limit
- Buy tab should not retain itens
- Open the management window with a command or maybe a stick/book
- Set the prices and move between buy/sell tabs just like DtlCitizensTrader

To only idea that I haven't figure out yet it's how the player will add some item in the buying tab that it doesn't have... For example: I wanna buy some diamond blocks, but I don't have anyone to setup my buying intentions... Could be done with commands, but that's dirty :D 

What you think?

**Comment by Dandielo** [comment]
Hmm... maybe it would be possible to create a "pick the item you want to buy" panel so you click on a "empty slot" and the it will open and you search for the rquired item?

**Comment by cranic** [comment]
Awesome idea!

**Comment by Dandielo** [comment]
Created a repo for this Idea. If you got anything in mind you can write there what you want

**Comment by cranic** [comment]
That's awesome, thx @Dandielo!
