### ISSUE TITLE
Idea - Disable chat messages

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#17]
With this new release it would be fine to have an option that disables the chat messages and buy with just one click. What u think?

**Comment by Dandielo** [comment]
I will make is just like you said, but I'm still debuging and this will be always enabled so when i'm redy the double click and messages are gone. Maybe they can be "enabled" but it may be more a "debug mode"

**Comment by cranic** [comment]
Excelent!
