### ISSUE TITLE
Issues with the last build

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#18]
- At the buy tab we have the text "Click to buy" instead of nothing or "Click to sell" when hovering itens.
- In the description of the last buil I can see `Beta version with prices in player inventory (when an item shows a price it can be sold)` but there is no item price while hovering the inventory, just the description.
##### Update:

I get the prices in the inventory window when creating a new NPC, but the prices are quite strange as you can see in the pic. And the olds NPCs don't show that price at all..

http://postimage.org/image/ei8501zcn/

**Comment by Dandielo** [comment]
going to check that

**Comment by Dandielo** [comment]
So far:
formating fixed, fixed prices in buy tab (now it won't show "click to buy")

**Comment by Dandielo** [comment]
ok should all work now, btw added dynamicaly changing items info when in manager mode, so when you in price mode you see prices, in limits mode limits, and stock mode, some info ift he items is from a pattern, if it listens to a patterns price or if it has stack price enabled

More over if you change the price it will be updated when you hover the item after the change (dunno why when you hover an item with an item in the cursor, nothing is going to be shown)

**Comment by cranic** [comment]
I'm going to check latter on.
