### ISSUE TITLE
Can't sell written books

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#19]
The title says it all.
When you buy the signed book, it's empty :)

**Comment by Dandielo** [comment]
yeah i know cose the written book, is as long as you do not reload it. It saves on the items id, data/durability and amount, nothing more. I still dont got a support for named things or books. and this wont be easy to add, cose i need to save each page of that book and the load it Oo

**Comment by cranic** [comment]
Well, that's ok, maybe in the future.
Can close if u wish :)

**Comment by Dandielo** [comment]
for now it's a bit impossible sorry 

closing
