### ISSUE TITLE
Chat messages when buying/selling

### ISSUE THREAD

**Issue by StephanScholz** [Dandielo/DtlCitizensTrader#21]
Hi, so far this is a great plugin. Keep up the good work :+1: 

My question now is: Is there a way to display it in the chat, when a user buys/sells stuff? If yes i didn't find...

**Comment by Dandielo** [comment]
not atm, I've removed it temporaty when i added the descriptions. I will add it with the next build, when I've fixed bankers. So far it will take 2-3 days. 

Sorry for this problem

**Comment by StephanScholz** [comment]
Well no harm done :). 2-3 days will be fine.

**Comment by Dandielo** [comment]
ok I've uploaded a new version with just added messages for completed transactions. I hope it's enough for the moment, still got a lot of work with recoding.

Here's the link, may be also found in downloads section
https://github.com/downloads/Dandielo/DtlCitizensTrader/dtlTrader2.0.1-bukkit-1.4.5-R02.jar
