### ISSUE TITLE
Patterns.YML

### ISSUE THREAD

**Issue by Discount-Milk** [Dandielo/DtlCitizensTrader#22]
You requested on the bukkit dev page for it so, here it is.

Blacksmith:
  prices:
    sell:
      267: 1.5
      256: 1.0
      257: 2.5
      258: 2.0
      292: 1.5
      261: 2.0
      262: .25 
  items:
    all:
    - 267 a:1 s:0 p:1.5
    - 256 a:1 s:1 p:1.0
    - 257 a:1 s:2 p:2.5
    - 258 a:1 s:3 p:2.0
    - 292 a:1 s:4 p:1.5
    - 261 a:1 s:5 p:2.0
    - 262 a:1 s:6 p:.25

**Comment by Dandielo** [comment]
hmm... werid on my side all things are working, it shows items in the traders inventory, after reload and restart.

May I know what steps your doing by assigning a pattern to a trader?

**Comment by Discount-Milk** [comment]
I use the command:

/trader create Test t:player

(This next step being in manager mode)
I use 

/trader pattern set Blacksmith

I restart the server, get back on it and I right click it... It's empty. It makes me sad when I see it's not there.

Is there something that I'm doing wrong?

**Comment by Dandielo** [comment]
yeah, player traders don't got patterns, cose they are generally created for players, so they got extra save mm, so they can't duplicate any item, and also can't use patterns to not get items from a pattern to the traders inventory. 

If you want use patterns you need to use market traders (t:market) (are full pattern traders) here you set items they buy and the will sell the amount the bought from a player, so when a player sells 32 wood to this market trader it will sell 32 wood from up now, but it can only sell 32 of it, or a player sells 16 wood , another buys 5 and another sells 12 so it will sell from up now (16 - 5 + 12) = 23

or you need to use Server Traders (t:server) (standard ones, so no "t:" flag required), where you set the pattern, item,s are infinite, or you can set limits for them (going to tell about limits more for patterns when I get the wiki updated)

I hope i could help :)

**Comment by Discount-Milk** [comment]
Oh thank you so much. I thought I was going crazy and I thought there was something wrong and I was going "PLUGIN Y U NO WORK"
