### ISSUE TITLE
NumberFormatException when restarting

### ISSUE THREAD

**Issue by StephanScholz** [Dandielo/DtlCitizensTrader#23]
So i just configured all traders on my server. After the daily restart some of them were gone, the other wont work anymore.

I postet the exception on pastebin: http://pastebin.com/wsbgc3ij

As you can see, your StockItem class throws that exception, with the Double.parseDouble method. I didn't look into it, but parseDouble definetly needs some exception catching :). Seems like the problem is a common one because of a missing decimalpoint.

**Comment by Dandielo** [comment]
nah just locale is wrong set xd for some ppl it's ',' for others it is '.' going to change just one thing, hsould be working after that

**Comment by Dandielo** [comment]
heres a new fixed version should be working, sorry for that...
http://dev.bukkit.org/server-mods/dtltraders/files/34-dtl-traders-v2-1-0-beta/

but anyway dont forget to make a backup from your save.yml

**Comment by StephanScholz** [comment]
Ahh ok. Thanks for the fast reply :)

**Comment by Dandielo** [comment]
if something happens just report it :)
