### ISSUE TITLE
Items doesn't stack after a visit to a trader

### ISSUE THREAD

**Issue by HerrGrim** [Dandielo/DtlCitizensTrader#27]
Using dtlTraders v2.2.3 Beta

When someone visits a trader with items in the inventory, they seem to acquire a status of their own, refusing to stack with new items from other sources.
Some items also keep a Unit Price and/or Stack Price when you leave the trader.

I tested this with 2 stones freshly mined from a wall.
Before I visited a trader, I threw one down on the ground, then visited the traded.
I did not mouseover the remaining stone.
When I left him, and picked up the stone from the ground, the two stones refused to stack.

Hope you can take a look at this, nothing major, but kinda annoying.

(Great plugin by the way).

**Comment by Dandielo** [comment]
sure, I alredy know why it's happening, thanks for reporting it ;) I wil ladd a fix in 2.2.5, 2.2.4 is actually incoming on bukkit fixing items named and enchanted to loose their enchants

**Comment by Dandielo** [comment]
Fixed :) It should now stack properly, also it should always remove all lores. 

Link for download:
http://dev.bukkit.org/server-mods/dtltraders/files/44-dtl-traders-v2-2-5/

**Comment by HerrGrim** [comment]
Great! Thanks alot. :)

**Comment by Dandielo** [comment]
Nothing big ;) You'r welcome :)
