### ISSUE TITLE
Error will trying to sell to trader

### ISSUE THREAD

**Issue by draxum** [Dandielo/DtlCitizensTrader#28]
I downloaded dtlTrader2.3.0.jar because of a previous issue with selling to the trader.  After restarting the server when I click to trade with the NPC the following error occurs:

21:09:55 [SEVERE] java.lang.NullPointerException
21:09:55 [SEVERE]       at net.dtl.citizens.trader.objects.Wallet.townyWithdraw(Wallet.java:78)
21:09:55 [SEVERE]       at net.dtl.citizens.trader.objects.Wallet.withdraw(Wallet.java:179)
21:09:55 [SEVERE]       at net.dtl.citizens.trader.parts.TraderConfigPart.withdraw(TraderConfigPart.java:54)
21:09:55 [SEVERE]       at net.dtl.citizens.trader.parts.TraderConfigPart.sellTransaction(TraderConfigPart.java:74)
21:09:55 [SEVERE]       at net.dtl.citizens.trader.types.Trader.sellTransaction(Trader.java:341)
21:09:55 [SEVERE]       at net.dtl.citizens.trader.types.ServerTrader.simpleMode(ServerTrader.java:245)
21:09:55 [SEVERE]       at net.dtl.citizens.trader.NpcEcoManager.onInventoryClick(NpcEcoManager.java:199)
21:09:55 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:09:55 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
21:09:55 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
21:09:55 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
21:09:55 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
21:09:55 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
21:09:55 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
21:09:55 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:1204)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.Packet102WindowClick.handle(SourceFile:31)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
21:09:55 [SEVERE]       at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)

**Comment by Dandielo** [comment]
There where several changes atm, so Towny/Factions/SimpleCLans Wallets are atm not supported in dev builds. 

Going to add them with some more wallets soon, sorry for that
