### ISSUE TITLE
Can't change prices?

### ISSUE THREAD

**Issue by abslodov** [Dandielo/DtlCitizensTrader#3]
Hi,

I'm currently trying to set up a simple block trader, I'm not able to change the prices, right and left clicking both show price: 0.

**Comment by abslodov** [comment]
Ok so, I just figured this out. The instructions or my brain were not very clear. Basically what I've done:
- To manage my server traders, put a stick in my hand (id: 280)
- Right click the NPC to activate management mode
- Before entering their inventory, separate out the blocks I want to trade/sell, for this example I will use dirt blocks. So I have a full stack in my inventory, I separate out 2 blocks and keep the rest in a stack
- I now right click the NPC I'm managing, click the lime wool to enter "buy" mode, because I want him to buy dirt blocks
- I left click the single dirt block and the console tells me "an item has been selected", so I drop it into his inventory.
- In order to change the price, I left click the black wool to enter "price" mode, as noted in the instructions, I need one of the following blocks in my inventory as well: 

wood counts as \* 0.01
log counts as \* 0.1
dirt counts as \* 10
cobblestone counts as \* 100
items not listed above count as \* 1
- In order to actually modify the price (let's use cobblestone) I left click and grab my cobblestone, then, while holding the cobblestone block, I left click the dirt block and the price increase by 100, to decrease the price, I right click the dirt while holding the cobblestone.
- I've now set the price that he will buy my dirt at to 200 coins per block. You could drop a stack in too etc..
- I can now right click the NPC with the stick, exiting manager mode, and right click him. I see the dirt block and I drop my stack in, selling 63 for 12600 wewt.

I understand now :]

**Comment by Dandielo** [comment]
I'm glad that's easy to figure out :)
Cose it was my main goal so it's easy to use :)

I hope you will enjoy it :) anyway if you need some help just mail me I
will try to answer as fast as I can :)

You can also mail me new features ok ideas ;)

Have a nice day :)
Daniel

**Comment by Dandielo** [comment]
And for the console message "Item has been selected". I will change it so
it will be more clear what's going on :)

**Comment by abslodov** [comment]
Awesome, thanks so much, I'll definitely keep using this and post any suggestions I may have, cheers
