### ISSUE TITLE
Switching from Buy to Sell menu stopped working. (Build 1.7.1)

### ISSUE THREAD

**Issue by MajorVictory** [Dandielo/DtlCitizensTrader#4]
It seems that when interacting with the trader in non-manager mode, the buy and sell switch have stopped working and I cannot view what the NPC wants to buy.

**Comment by Dandielo** [comment]
I've already fixed that in ver 1.7.11 (it's still in  approval on
dev.bukkit)
Anyway thanks for the feed back :)

And sorry for the glitch
