### ISSUE TITLE
[Bug] Class not found with latest Denizen

### ISSUE THREAD

**Issue by spaceemotion** [Dandielo/DtlCitizensTrader#40]
Getting this error with the latest version of denizen and dtltraders:
http://pastebin.com/NVPdaypV

Denizen changed the NPC class, just renaming the references should work :)

**Comment by Dandielo** [comment]
ok thanks a lot going to push this when ready with the new locale... atm still working on it

**Comment by Dandielo** [comment]
Fix comes with the next build #126

**Comment by spaceemotion** [comment]
Thank you!

**Comment by Dandielo** [comment]
Build is on jenkins :)
