### ISSUE TITLE
[Bug] Player limits not working

### ISSUE THREAD

**Issue by spaceemotion** [Dandielo/DtlCitizensTrader#42]
_Problem_
Player limits are not working as intended

_How to reconstruct_
Just create a new trader, add some stuff to buy and set the player limit to 3. Even as non-op you can buy 4, 5 or more items even though you should not be able to

Please fix this!

**Comment by Dandielo** [comment]
mhm going to look at this, sorry for the problems

**Comment by SolidGeek** [comment]
Dandielo please fix this bug as fast as you can, I really love your plugin, but I can not really use it for my server because of the lack of the Limit function! I hope you see this comment, and thanks for your work, I really appreciate it, it is such a great plugin :+1: :smiley:

**Comment by Dandielo** [comment]
Going to start the work on this after i got basics working with permissions and management mode. Sorry for the delay :<
