### ISSUE TITLE
Suggestion for Dtltrader Banker

### ISSUE THREAD

**Issue by draxum** [Dandielo/DtlCitizensTrader#43]
One suggestion for the Banker of Dtltrader would be to have a multi-tab bank.  Say use different color wool to represent the different tabs at the bottom of the banker display.  The first tab could be used right away and the others would have to be unlocked by purchasing the bank tabs from the server economy.

**Comment by Dandielo** [comment]
Drauxum click on the trader with a book :) and click on the second white wool :) also you can look into the config file, there are already settings how much a tab should cost, also when in the "book" mode yuo can change the "wool" into nay item in your inventory, just click on the "row" you will see there

**Comment by draxum** [comment]
That just made your banker even better!
Great Job!
