### ISSUE TITLE
Modded items losing data on opening trader inventory

### ISSUE THREAD

**Issue by Nemeis** [Dandielo/DtlCitizensTrader#44]
On opening a trader's inventory, either in manage mode or for regular trading, modded items in my inventory lose information/data. Industrial craft tools lose their charge, and redpower bags lose their contents.
Renamed modded items retain their names.

Possibly related to how item descriptions are changed to show price?

Running the latest version of dtlTraders, on a mcpc+ server.

**Comment by Dandielo** [comment]
hmm... was it working before? Or it was always broken?

**Comment by Nemeis** [comment]
haven't tested on older versions of dtlTrader's, but it worked fine with citizens 1's traders. This may not be a good comparison, though, as those traders didn't have the neat gui tricks yours does.

**Comment by Dandielo** [comment]
It might be a larger problem because of the descriptions, may you send me your whole server? would be easier to test it for me

**Comment by Nemeis** [comment]
Sure. Sent to your email. Thanks for looking into this.

**Comment by Dandielo** [comment]
daniel.penkala@gmail.com

**Comment by Dandielo** [comment]
I might have a solution after I'm done with patterns.

**Comment by Dandielo** [comment]
About that bug, I already know whats going on but to make a workaround will take some time

**Comment by Nemeis** [comment]
That's good to hear. I've got plenty of other things to get worked out on the server, so no rush. Its also possible I'm the only one using your plugin who's experienced the bug :) (aside from my couple of users/friends on the server)

**Comment by Adondriel** [comment]
Yeah, i noticed this kinda, the lore will disapear, but the names still work.

**Comment by Dandielo** [comment]
Ok I've already figured out where the problem might lay, also added a small fix for it, i just dunno if it will work with modded items. If it will be on jenkins I'll let you now

**Comment by Dandielo** [comment]
Try the latest build

**Comment by Nemeis** [comment]
A quick test on my 1.4.7 server shows no difference. I won't be able to test on 1.5.1 until the mods update.

**Comment by Dandielo** [comment]
Thanks for the info

**Comment by Dandielo** [comment]
recheck please if it's possible on 1.5.1

**Comment by Nemeis** [comment]
I threw together a server with the dev versions of industrial craft and forestry, as well as latest version's of citizens, dtltraders etc. 
Forestry's backpacks were cleared, industrial craft's electric tools lost their charge, when I had them in my inventory and interacted with a trader. I was not able to test redpower's bags, since that mod hasn't updated. To the best of my knowledge, they all store their data in the item's nbt, so i wouldn't expect redpower's to work either.

On a side note, the server was buggy enough that the npc's didn't stick around after a server restart O.o (probably an issue with mcpc+)

Just out of curiosity, how are you trying to preserve item nbts?

**Comment by Dandielo** [comment]
atm i'm trying to make a workaround using class names, so when an item has a NBT and it's one i can't recognize I try to make it untouchable by my trader lore plugin but it looks like i need to get more into the server core, so it will break atm the portability of traders. Anyway I will try another fix today or tomorrow

**Comment by Dandielo** [comment]
I've made some Advanced Java Magic, so you may try the latest build, but it's only for 1.5.1!!!
