### ISSUE TITLE
[BUG] All commands - see /trader help error

### ISSUE THREAD

**Issue by PoxyDoxy** [Dandielo/DtlCitizensTrader#45]
Any of the commands possible for DtlCitizensTrader DO NOT WORK, instead they all reply back with "See /trader help for a list of commands."
When the other command is used "/help DtlCitizensTrader" it DOES return with "Below is a list of all DtlCitizensTrader commands." It shows two commands, "/banker" and  "/dtlcitizenstrader:trader:".
Upon using /dtlcitizenstrader:trader it comes back with the full list of commands but again they all return with "See /trader help for a list of commands.".

My Server is running 1.4.7 R1
As for the plugins i disabled ALL of them while to narrow down the problem however it is not due to other plugins. I have started the server with just these plugins: Citizens2, DtlCitizensTrader and Vault (All latest builds).

I have used previous builds and they give me errors (to be expected) HOWEVER what they can do is execute the commands, the commands get parsed however return with errors, DtlCitizensTrader isn't even parsing the commands. Not entirely sure how other servers have gotten this working as they are running 1.4.7-R1 and work fine, i dont know what version they are running.

*Something weird that i noticed is that all the plugins extract to their appropriate folders upon server start however Vault does not, it still becomes enabled however does not have a cache/config folder. Not entirely sure if this is normal.

Hope this is fixed soon,
Poly359

**Comment by Dandielo** [comment]
Ok then, Please send me your bukkit build, Citizens 2 build, and the Trader build you are using.

Also I got the feeling you got CitiTraders running at the same time with dtlTraders. Because it quite abnormal for "Essentials" or any other plugin like this one to show the full command name (with the "plugin name" as prefix).

Not only the prefix is telling me you got CitiTraders or a similar plugin, also what's weird I did never added the message "See /trader help for a list of commands.".

An you did not give me any information what build you are using. With previous you mean versions 2.2? 2.3? 2.4? or jenkins builds #149 #150? 

About starting this plugin with as less plugins as you can... you need to remember to always have an Economy plugin running or this plugin wont even start...

info("Economy plugin not found! Disabling plugin");
this.getPluginLoader().disablePlugin(this);

So narrowing the problem was a good idea, but you narrowed it a bit too much... 

Next. Vault does not extract because it does not need to extract. So it wont ever extract to a folder. 

Pleas send me information I require because with this "part" I can't do anything right now

**Comment by PoxyDoxy** [comment]
Thanks for replying so quickly.
The only things i am using is those listed above so im not using CitiTraders.
About the plugin not starting unless there is an Economy: I understand now, ill enable it and try again to see if there is a difference, at the moment i am using essentials economy.
Sorry but the previous versions i tested were indeed Jenkins builds, i tested the top 10 before i gave up.
The following are the plugins and their versions:
  -- Bukkit 1.4.7-R1.0 # 2624
  -- DtlTraders = v2.4.0
  -- Vault = v1.2.23-b301
  -- Citizens2 = v1.2.3

==============MASSIVE APOLOGY=======================
here i am sitting here dreaming, completely oblivious to the fact that there is a giant error message in my server log every time DtlTraders tries to load haha, Derp.
Then again it is kind of hard to see when it flies by in the massive amount of text on every reload.
This is the error log when DtlTraders tries to load.

The -------- is for spacing
20:54:53 [INFO] [DtlCitizensTrader] Enabling DtlCitizensTrader v2.4.0
20:54:53 [INFO] [DtlCitizensTrader] Loading bank accounts
20:54:53 [INFO] [DtlCitizensTrader] Loading locale
20:54:53 [INFO] [DtlCitizensTrader] loading patterns
20:54:53 [INFO] [DtlCitizensTrader] Using Essentials Economy plugin
20:54:53 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
--------at net.dtl.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:143)
--------at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
--------at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
--------at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
--------at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:282)
--------at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:264)
--------at org.bukkit.craftbukkit.v1_4_R1.CraftServer.reload(CraftServer.java:593)
--------at org.bukkit.Bukkit.reload(Bukkit.java:184)
--------at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
--------at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
--------at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
--------at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchServerCommand(CraftServer.java:506)
--------at net.minecraft.server.v1_4_R1.DedicatedServer.al(DedicatedServer.java:260)
--------at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:225)
--------at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
--------at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
--------at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
--------at java.net.URLClassLoader$1.run(Unknown Source)
--------at java.net.URLClassLoader$1.run(Unknown Source)
--------at java.security.AccessController.doPrivileged(Native Method)
--------at java.net.URLClassLoader.findClass(Unknown Source)
--------at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
--------at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
--------at java.lang.ClassLoader.loadClass(Unknown Source)
--------at java.lang.ClassLoader.loadClass(Unknown Source)
--------... 17 more

Do you still want me to put the server in a Zip file for you to analyze? What will be attached is a fresh server using the same bukkit version ( 1.4.7 R1.0 #2624) and the same plugins, the outcome is still the same.

**Comment by Dandielo** [comment]
You know that Citizens Bukkit page has both Citizens 1 and Citizens 2 versions? 

And this one "v1.2.3" is the old Citizens 1 Version, so you need to download Citizens 2 (best from Jenkins) and also use then my Jenkins build so use for both Citizens2 and DtlTraders latest Jenkins Builds

**Comment by PoxyDoxy** [comment]
Thank you so much! 
I downloaded citizens 2.0.7  from Jenkins (http://ci.citizensnpcs.com/job/Citizens2/)  and DtlTraders 2.5.0 from Jenkins  (http://www.wbs-wireless.com:9090/job/dtlTraders/154/) and it works! 
I thought i was downloading Citizens 2  but the site must of been pointing me to the Citizens1 builds. I remember them mentioning that there was Citizens1 too.
Keep up the great work!

**Comment by Dandielo** [comment]
You are welcome :D 

With greetings Daniel ;)
