### ISSUE TITLE
Can't sell to traders

### ISSUE THREAD

**Issue by Adondriel** [Dandielo/DtlCitizensTrader#47]
My users cant sell to traders, OPs can sell, normal users cannot.
Occasionally my users can sell 1 item at a time, but then they can't, Sometimes they get a "you dont have permission" error and other times they get "someone doesnt have enough money"

no error logs.

**Comment by Dandielo** [comment]
Can you pleas specify the trader version you are using?

**Comment by Adondriel** [comment]
2.4.3, with citizens... Citizens v2.0.7-SNAPSHOT (build 742)

**Comment by Dandielo** [comment]
hmm... looks like i got somewhere a permission bug within 2.4.3. it might take some time till i find it. I think you can already try 2.5, it should be for the easiest things stable enough :)

**Comment by Adondriel** [comment]
Ok, ill try it out.

**Comment by Adondriel** [comment]
It is still broken in 2.5 aswell.

**Comment by Dandielo** [comment]
ok thanks for the feedback going to look into it as only I wake up (got atm 3am here)

I should get it working till tomorrow evening

**Comment by Dandielo** [comment]
looks like this issue is solved, going to close it for now
