### ISSUE TITLE
Renaming NPCs can cause stock loss

### ISSUE THREAD

**Issue by CyanLights** [Dandielo/DtlCitizensTrader#48]
If you make an NPC, and put things into its sell or buy windows, and re-name that NPC any time after items have been added, the resultant NPC has an empty shop window, and items have to be re-added. Before today, we had no problem re-naming NPCs after their shops were set up.

**Comment by Dandielo** [comment]
Need more information about this bug

**Comment by Dandielo** [comment]
Does this still happens?
