### ISSUE TITLE
Music Discs Not Retaining Price

### ISSUE THREAD

**Issue by CyanLights** [Dandielo/DtlCitizensTrader#49]
We have found that music discs do not work with traders, at least on our server. Putting them in a shop and setting prices on them works fine, but a few hours later (possibly after each server restart?), they are once again set at $0.

**Comment by Dandielo** [comment]
does this only happens for music discs?

**Comment by Catorii** [comment]
Yes, just for music discs. We input prices on them, and they stay, but after a server restart (or possibly just after a little while) the prices reset to 0 on all of them. We do not have this specific problem with other items.

**Comment by Dandielo** [comment]
prices should persist now, please check it
