### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by FluiD96** [Dandielo/DtlCitizensTrader#5]
If server stop's Prices don't save on any ID... Fix saving prices on server stop ( ver 1.9.6)

**Comment by Dandielo** [comment]
Hmm... can you describe it more? Does it happens when you'r overriding pattern prices? or when you'r setting normal prices? or always?

**Comment by FluiD96** [comment]
I don't know how to set patterns i'am just set a managing mode and set price's , then "STOP" server , and after start all price's gonna 2 be 0$.
P.S. Sorry 4 my bad eng.

**Comment by itsmethatswho** [comment]
I am having the same problem as well.  There is no error that I can see being created for the server.  I am setting prices on my trader both for selling and buying.  Then I restart the server come back to the merchant and everything is reset to 0.  It's a server type trader and it's the first trader I've created so my patterns file is empty.  I'm posting my config just in case it helps, but I think it is the default.  Trying to recall if I changed anything in it.

Is there anything that I need to do to save the prices like respawning the trader before I restart the server?

locale: 
  file: english.loc
wands:
  manage: 280
  settings: 340
trader: 
  patterns:
    file: 'patterns.yml'
    default: ''
  inventory-navigation: 
    sell-tab: '35:5'
    buy-tab: '35:3'
    manage-price: '35:15'
    manage-buy-limit: '35:12'
    manage-global-limit: '35:11'
    manage-player-limit: '35:12'
    return: 35
    amounts-return: '35:14'
bank: 
  tab-size: 3
  withdraw-fee: 0.0
  deposit-fee: 0.0
  max-tabs: 9
  tab-prices: 
    tab2: 100.0
    tab3: 200.0
    tab4: 500.0
    tab5: 1000.0
    tab6: 2000.0
    tab7: 5000.0
    tab8: 10000.0
    tab9: 50000.0
  player-accounts:
    file: player_accounts.yml
  guild-accounts: 
    file: guild_accounts.yml
money-bank:
  exchange-item: 388
  item-value: 10.0  
logging: 
  general: 
    enable: true
  player-trader: 
    enable: true 
    file: player_trader_logs.yml

**Comment by Dandielo** [comment]
Ok, I've found that bug ;) 
I will upload it when I'm back home :)

**Comment by FluiD96** [comment]
Thanks

**Comment by itsmethatswho** [comment]
Awesome thank you!

**Comment by Dandielo** [comment]
I've uploaded the new ver on dev.bukkit.org, now we need only to wait it will be approved by the bukkit team :)
