### ISSUE TITLE
Firework Metadata Structure

### ISSUE THREAD

**Issue by CyanLights** [Dandielo/DtlCitizensTrader#50]
Fireworks don't work with traders. If you create crafted fireworks (i.e. a creeper-shaped firework) and put them into an NPC, they turn into the default fireworks with no effects and no colors.

**Comment by Dandielo** [comment]
As i thought it's saved in another metadata structure, I might try to fix it right now because it's not a lot of work. It's just reading the data and create a format string for it. Might be able to fix it in the next hour.

**Comment by Dandielo** [comment]
Just tell me, because I've not played minecraft for quite some time, does fireworks may have more than 1 color and may they have more than 1 effect?

**Comment by CyanLights** [comment]
Yes they can. I believe fireworks can have as many colors as are available to use with them, as well as effects.
There are a ton of possible combinations.

**Comment by Catorii** [comment]
They can have as many colors as you can fit, I think, as I've done 3 colors on fireworks without trouble. They also can  have added trail/twinkle effects (separate from the main burst effect) via diamond/glowstone dust, if I remember correctly. For the actual firework explosion, they can have a star-shaped, creeper-shaped, burst, large ball, or small ball explosion. Each type of explosion uses a different ingredient added to the Firework Star when it's created.

Hope that's enough detail. Thank you so much for looking into this.

**Comment by Dandielo** [comment]
Ok, atm just finished with a simpler issue, allowing to put into trader stock dyed item, and because i fixed also some other things heading now to debug fireworks which still does not works as i would like :P But progress is visible :)

**Comment by Dandielo** [comment]
And it's done :) You might also use it within patterns :)  build #183

the pattern format goes like this fw:<trail>.<flicker>.[red-green-blue].[red-green-blue].<type>

<...> - are optional,  [...] - are required and to remember , first is color second is fade color

also the last <type> takes values like BALL, BALL_LARGE, STAR, (and i dont know the other ones:P )
