### ISSUE TITLE
Critical Bug (Breaks Traders Completely)

### ISSUE THREAD

**Issue by CyanLights** [Dandielo/DtlCitizensTrader#51]
When switching tabs in management mode, i.e. from price to stock, there is sometimes this horrible bug where a certain item in the NPC will copy itself to the first available slot in the NPC inventory.

If there is more than one stack of that bugged block / item, it will reproduce either a full or half stack, plus 1. The rest will be missing. Other times, it will copy itself and leave part of the stack of the original in place.

Also, if you have a price set on a bugged item before it bugs, it will permanently list the price as "pattern price" after the bug happens.

If you remove the bugged item stacks and try to put fresh ones in, they just start the replicating problem all over.

However, you can still purchase bugged blocks / items from the NPC without issue.

When this happens, the trader becomes irrevocably and indefinitely broken and you have to make a new one from scratch.

**Comment by Adondriel** [comment]
This isnt a bug, what is happening is before you switch to the pricing mode, you click on an item in your inventory. this causes that item to then be selected, and added to the list. I had this problem, it isnt a bug, it is just user error, retry with a new npc.

**Comment by CyanLights** [comment]
I'm afraid it is a bug and it has been detrimental to my staff members who are in charge of my server's economy. The dev has confirmed that there are some critical issues with how the trader data is being copied and saved. This was discussed on bukkit dev and  Dandielo asked me to submit it as a ticket here.

**Comment by Dandielo** [comment]
I could only reproduce a similar issue with an item from the traders stock, but only it changes the item to jump to the first available slot. Not event 1 time i got a new item added to the stock. I might anyway add a selecting clear before each management change

**Comment by CyanLights** [comment]
Have you tried this with say a stack of obsidian or nether brick slabs? Those were items in one of our shops that caused these problems often.
Also, could you double check that the bug can't be triggered by normal players purchasing items? We have found NPCs in our store messed up sometimes without us touching them...

We really appreciate your help!

**Comment by Dandielo** [comment]
does this still happen?

**Comment by CyanLights** [comment]
Yes it does.
