### ISSUE TITLE
do not have permission to select the buy even for op

### ISSUE THREAD

**Issue by wopper87** [Dandielo/DtlCitizensTrader#52]
A am the owner of the map and I can do all the commands for the /trader /npc (the basic /npc did not work until the latest build) but when I go into management mode for example on dtl trader it will allow the first selection of sell (or stock) but I can not set up a buy it says i do not have permissions to do so. in my permission folder for PEX I have myself as all permission '*' and I have even tried taking that off and listing all the permission for both citizens and dtl. This does the same thing when I try to use the cititrader plugin but on there it just will not allow me to select a block for the buy option. There are no errors that come up in the console and it says it loaded. I have tried every build for citizens2, dtl, cititrader and bukkit but nothing changes so far. I can issue all other commands under the earth but i can not get them to allow the buy. the config file is the default setup I have not changed a thing in there.

**Comment by Dandielo** [comment]
may you send me anyway your permission setup? got also pex and would like to try it out

**Comment by wopper87** [comment]
I figured it out. I had the 2.43 version with the recommended build of craft, and the latest build of all other dependent plugins. It works in 2.40 but not the 2.43.

**Comment by Dandielo** [comment]
2.4.3 got some weird permission bugs... i dunno why ;/
