### ISSUE TITLE
[Bug] Prices Reseting

### ISSUE THREAD

**Issue by marcosds13** [Dandielo/DtlCitizensTrader#58]
Every time i Restart the server the prices of Traders reset, in Config the "p:(price" just disappear

In version 2,5,0 Alpha

**Comment by Dandielo** [comment]
is it still disappearing? Btw you mean "p:price" right?

**Comment by marcosds13** [comment]
i have found the problem , prices from other versions dont work in this version

**Comment by Dandielo** [comment]
can you show me the problem? Because they was working for me
