### ISSUE TITLE
[Bug] Stack Price dont work like the another versions

### ISSUE THREAD

**Issue by marcosds13** [Dandielo/DtlCitizensTrader#59]
The Stack price with this Version is Weird is like Pattern Price + Stack Price together.

In version 2.5.0 Alpha

**Comment by Dandielo** [comment]
It was intended to work in another way, but how it works now i can't say you, I'm going to fix this in the next 1-2 days :) This will allow you to create multiple amounts from a stacked item, like you got 3 bred fo 1$ then you can also sell 6, 9, 12... etc :)

**Comment by marcosds13** [comment]
thanks :D

**Comment by Dandielo** [comment]
It should work now :) also allowing to add multiple amounts, with counting the price for each additional amount after the main amount. Please tell me if it works, and sorry that it took so long
