### ISSUE TITLE
[Bug] Some Commands not working

### ISSUE THREAD

**Issue by Vorox3** [Dandielo/DtlCitizensTrader#60]
In both 2.4.0 and 2.4.3 the create trader commands and management commands don't work(and /trait). I have Vault installed with this like it told me on the forums. I have had admins of other servers tell me this is a bug. Please Help ASAP

**Comment by Dandielo** [comment]
commands has changed a bit I will update the wiki today evening to version 2.5.0 :)

**Comment by Dandielo** [comment]
Wiki is up to date with all working 100% commands.
