### ISSUE TITLE
enchanment books

### ISSUE THREAD

**Issue by Danton1983** [Dandielo/DtlCitizensTrader#62]
When the shop sells the enchanted book, the books looks right in the shop but when purchased it is just simply an "enchanted book" you can't do anything with it.

Using latest dev build

**Comment by Dandielo** [comment]
going to fix this today

**Comment by ghost** [comment]
Dandielo I havent seen you on denizen/citizen or in the dtlprojects chat for some time now! Glad to hear back from you.

**Comment by Dandielo** [comment]
was quite busy, and still got lot thing to do but atm i got much more time.

**Comment by Dandielo** [comment]
Fixed
