### ISSUE TITLE
bank duplicate issue

### ISSUE THREAD

**Issue by Danton1983** [Dandielo/DtlCitizensTrader#63]
if i move an item in the bank to the tab row it throws the item and leaves it in the bank and players can duplicate items

**Comment by Malachiel87** [comment]
I confirm this, real annoying bug, is possible to temporany disable tab function or a trick for fix temp it?

**Comment by Dandielo** [comment]
I got it' a fix is incoming :)

**Comment by Dandielo** [comment]
ok no more duplication on my test build, now it's makes items disappear lol

**Comment by Malachiel87** [comment]
nice progress xD

**Comment by Dandielo** [comment]
Tbh, I'm atm so iritated about my code, that I'm going to make a total recode, all from scratch soon... 
So be prepared to ask for features as long as I'm projecting the code structure
