### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by Catorii** [Dandielo/DtlCitizensTrader#64]
On our server, we're currently having problems getting the permissions to work with traders. We're trying to set it so only certain ranks can use specific traders, but it doesn't seem to be working. No matter what we do, the permissions remain open to everyone.

Also, after seeing that permissions were buggy in one of the older builds, we tried updating to the 2.5.0 dev build, and got the same results.

Commands currently being tried that aren't working: 

```
    - -dtl.trader.*
    - -dtl.*.*
    - -dtl.trader.options.*
    - -dtl.trader.options.buy
    - -dtl.trader.options.sell
    - -citizens.*
    - -citizens.*.*
    - -dtl.trader.types.player
    - -dtl.trader.types.server
    - -dtl.trader.types.market
    - -dtl.trader.types.enchant
    - -dtl.trader.
```

We'd appreciate help with this.

**Comment by Dandielo** [comment]
I will check those perms on my side, may I know how you want to have set them?

**Comment by CyanLights** [comment]
Basically, we have two survival worlds. One is normal and the other is for donators.

The normal world has a NPC shop in it, and the donator world has a special donator NPC shop.
Basically, we allow non-donors in the donator world, but we want to revoke their permissions so they can't use the donator shops.

**Comment by Dandielo** [comment]
atm (with 2.5) you might create a pattern with a donor item tier.

<pre>
donor_pattern:
  type: item
  donor:
    sell:
    - id:data p:price etc...
    - id:data p:price etc...
    - id:data p:price etc...
    buy:
    - id:data p:price etc...
    - id:data p:price etc...
    - id:data p:price etc...
</pre>

and add only donors following permission

dtl.trader.tiers.donor

This should work for you :)

**Comment by Dandielo** [comment]
This will still allow them to open the shop but that shop should be empty for them

**Comment by Catorii** [comment]
Sounds good. But when we used 2.5 last, it bugged out and set all our prices to $0.

**Comment by Dandielo** [comment]
hmm... can you join IRC channel? I can try to fix that right now 

link here: http://webchat.esper.net/?nick=random_dtl_...&channels=dtlProjects&prompt=1

call me when you get in
