### ISSUE TITLE
Written book bug

### ISSUE THREAD

**Issue by ecp4224** [Dandielo/DtlCitizensTrader#66]
Opening a trader with a written book in your inventory will remove all the data for the written book.

**How to reproduce**
1. Write a book and keep it in your inventory
2. Right click on a trader
3. Close the trade window
4. Open your inventory and look at the book.

**Comment by Dandielo** [comment]
Should be fixed with latest build

**Comment by ecp4224** [comment]
Yup, its fixed!

However, putting the book into the shop causes the same problem. But I think another issue should be made for that..

**Comment by Dandielo** [comment]
books atm not supported. Thats why they loose their data. I need for this to create a whole system ;) because i need to save books by myself :P
