### ISSUE TITLE
Invisible items

### ISSUE THREAD

**Issue by Dandielo** [Dandielo/DtlCitizensTrader#7]
Items that a player can't buy won't show up in the traders window

**Comment by FluiD96** [comment]
Are you sure that invisible? I think that added item with zero count. 
 **_You can see item in stock at managing mode_**, but if normal mode stock buy/sell you cant see, buy/sell that. In fact in **SAVE** file **Citizens** directory item is added with zero count, i'll check it again...

**Comment by Dandielo** [comment]
yeah it's already implemented in the player trader so when some1 has bought all items a player had for sell, thei will be invisible for "Buying", it won't disappear in manager-mode so you don't need to set from begining the amounts and prices for that item just add new items for sell

**Comment by FluiD96** [comment]
Ohhhh, realy good news, awaiting for new updates, i'am programmer too, may be see your code..
