### ISSUE TITLE
Bug when Right click a trader

### ISSUE THREAD

**Issue by Hpix** [Dandielo/DtlCitizensTrader#71]
I'm having an error after a few minutes online:
http://pastebin.com/caAzY9FC
Using 2.5.0

**Comment by wolfbane8653** [comment]
Having the same issues.
MC: 1.5.2-R0.2-b2772

Here is a shortened log file. 

https://www.dropbox.com/s/xkmqmz1j92ojgef/server.log

**Comment by Dandielo** [comment]
Try the latest build please, made some changes so it might be fixed : )
