### ISSUE TITLE
Feature Requests for 3.0

### ISSUE THREAD

**Issue by Danton1983** [Dandielo/DtlCitizensTrader#74]
Also on occasion when adding items to a shop they disappear, not a huge deal as I am an admin and can spawn more.

I'd love to see Banks
Player Bank
Guild Bank

I'd like to buy permissions or commands etc not just items.
Custom named potions just turn to potions in the shop, would love to have this fixed.

**Comment by Dandielo** [comment]
Potions will be added without any probs :) bankers will be done later.
I will also try to allow you selling permissions. How to sell commands would be quite more hard, possibly it would need another plugin

**Comment by Dandielo** [comment]
If you can please create this issue also on this repo:
https://github.com/Dandielo/dtlTraders/issues

Thanks :)
