### ISSUE TITLE
Pattern File Formatting

### ISSUE THREAD

**Issue by CyanLights** [Dandielo/DtlCitizensTrader#75]
Hi,

This isn't a bug, but I am unsure of how to start a pattern file. Can you give me an example?
Is it something like:

Patterns:
 pattern_name:
   type: pattern_type
   all:
- ...
  sell:
- ...
  buy:
- ...

The first line is what is confusing me. The wiki doesn't say how to start the file, and most yml files have a header.

**Comment by Dandielo** [comment]
there is no header, so you just start each pattern with it's name and thats all :) 

P.S. If you got any feature requests, issues or if you want to have something changed with 3.0 please look at dtlTraders 3.0 issues :) 

https://github.com/Dandielo/dtlTraders

**Comment by CyanLights** [comment]
Very good. Thank you.

And I'll meet with my team and see if we can come up with any suggestions. Thanks, Dandielo :)

**Comment by Dandielo** [comment]
Do it as fast as possible :) Anyway manager mode changed a bit :P 

Now adding and removing items will be done using sth like a "Lock" statement, so you will unlock the stock to add items to it, you can shift click, r.click l.click as much as you want, what you can imagine you can click :P If you are done with your magic, just lock the stock and all items are saved :)

all other things works in the same way like in previous versions :) I hope you will like it ^^

**Comment by CyanLights** [comment]
Oh very cool. I think that will be a pretty good way of going about it. Cat and k5 will be glad to hear.

Also, I had a question: If your pattern doesn't include items in the "all" or "buy" categories, do you put like - . there, or just leave those sections out entirely?

**Comment by Dandielo** [comment]
just leave them entirely

P.S. if they want to test it, here is my last stable build
http://speedy.sh/YJCgb/dtlTraders.jar

So far there are only working server traders, and you will need to create them by using /trait trader and /trait wallet

Any specific settings needs to be set in the save file :P

Manager modes allows so far adding, removing and changing items for sell stock, besides this price managing works + some messages. (not all config values works)

You can have a log what a spam generator this plugin is when you set debug to "info" ;)

**Comment by CyanLights** [comment]
Um... This just happened when I tried to apply the pattern.
http://pastebin.com/KtiTSeAV

**Comment by Dandielo** [comment]
Somehow you just omitted some of my system checks and allowed to have an item with no amounts lol... 

can I have a look on the pattern?

**Comment by CyanLights** [comment]
Of course:
http://pastebin.com/UZmUWLKK

Also, I'll try the dev build tomorrow if I find time =)

**Comment by Dandielo** [comment]
try to change 

p: 225000

to

p:225000

this whitespace may be the problem maker

**Comment by CyanLights** [comment]
Thanks. I fixed that, but it gives me this now:
http://pastebin.com/4KgEJerh\

This is my pattern file:
http://pastebin.com/QWRgAEbW

**Comment by Dandielo** [comment]
first link broken :P

**Comment by CyanLights** [comment]
http://pastebin.com/4KgEJerh

**Comment by Catorii** [comment]
^ Any help we can get with this would be great. We're so close to finally having our special traders active! :)

**Comment by Dandielo** [comment]
Sorry, forgot abut this because was working on 3.0. This happens when you want to apply a pattern to a trader with a command right?

**Comment by CyanLights** [comment]
Yep

**Comment by Dandielo** [comment]
What command are you using? I mean how the command looks like that you use

**Comment by CyanLights** [comment]
I think I was just using the wrong command. If I were to edit saves.yml and add the pattern to the trader that way, where do I add it? There are two pattern sections under the trader.

**Comment by Dandielo** [comment]
there should be only one section named "patterns". You need to add like items in a list, I just don't remember if it was in the order of Pattern_name priority or priority Pattern_name, but I would try the second order first.
