### ISSUE TITLE
Suggestion: /managermode Command

### ISSUE THREAD

**Issue by itsmethatswho** [Dandielo/DtlCitizensTrader#8]
Hello again!  I was wondering if it would be possible to activate Manager Mode for a trader with a command.  Right clicking with an item stops working for me if I trait the NPC as a denizen as well.  I get around it by removing the denizen trait temporarily, but would be a little more convenient/straight forward to just type something.

**Comment by Dandielo** [comment]
np :) i will add it

**Comment by itsmethatswho** [comment]
Awesome thanks!

**Comment by Dandielo** [comment]
ok i've added /trader manage <name>
and /trader open

first turn's on off the manager mode 
second opens the inventory to manage

**Comment by Dandielo** [comment]
i hope it's what you want :)

**Comment by itsmethatswho** [comment]
Sountds great, thanks!

**Comment by Dandielo** [comment]
added in RC2.0 (it can be downloaded from this page)
