### ISSUE TITLE
DtlTrader not working with current version of bukkit?

### ISSUE THREAD

**Issue by abslodov** [Dandielo/DtlCitizensTrader#9]
Hey Dandielo,

I can't get traders working at all with the following versions:

Bukkit: 1.3.2 build# 2396
Citizens2: build# 495
DtlTrader: build# 1.9.61

Here is the error I keep getting when I try to manage a brand new trader...
http://i.imgur.com/g7NMj.png

I have the correct permissions, I'm the OP anyways, but nothing....

Bankers seem to work pretty well, but I can't even set up a trader :[

I know 1.4 is coming and a big deal etc...please help, I really love this and want it to work! :]

**Comment by Dandielo** [comment]
traders permission setup is a bit broken as i see, and alredy fixed that {entity}s message 

I will put a new vers tommorow (atm got 10 days off :D)

**Comment by abslodov** [comment]
dandielo, thank you <3!!

let me know if i can help you out i have a lot of suggestions :]

**Comment by Dandielo** [comment]
hmm can you send me you'r permission setup? i need to try this out

**Comment by Dandielo** [comment]
a new trader ver is in the downloads section

**Comment by abslodov** [comment]
Awesome! Gonna try it!

Still need my setup? here is what I use:

Bukkit: 1.3.2-R2.0, build# 2396 
Citizens: 2.01, build# 495
bPermissions: v2.9.24 for CB 1.3.2-R1.0
BOSEconomy: v0.7.3.1a [1.3.2+]

Here is a copy of my perms:
http://pastie.org/5127586

Here is the full list of plugins I'm running, let me know if you'd like anything else:
bPermissions, neoPaintingSwitch, BOSEconomy, Vault, Questioner, Monster Apocalypse, dynmap, Register, BookRules, mcMMO, SecureChests, Essentials, Citizens, EssentialsProtect, Towny, EssentialsSpawn, Alchemist, RecipeManager, EssentialsAntiBuild, Denizen, Sentry, EssentialsChat, Blacksmith, DtlCitizensTrader, TownyChat, Builder, Dynmap-Towny

**Comment by abslodov** [comment]
ok, just tried this build, still can't manage the traders,
http://i.imgur.com/cTQsI.png

I'm using the perms I linked you above, and I'm both a server OP and an 'admin' in my permissions so I should definitely have access unless one of my other plugins is messing this up. I can't tell if it's because of another plugin though, need a blank server.

**Comment by Dandielo** [comment]
hmm all should be fine anyway going to add bPermissions as a supported plugin maybe it will repair it

**Comment by Dandielo** [comment]
fixed
